//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoConfigNetJM.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoConfigNetJM.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Automatizacion de configuracion de redes JM.
        /// </summary>
        internal static string appName {
            get {
                return ResourceManager.GetString("appName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1-05.2019.
        /// </summary>
        internal static string appVersion {
            get {
                return ResourceManager.GetString("appVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add Vlan.
        /// </summary>
        internal static string btnAddVlan {
            get {
                return ResourceManager.GetString("btnAddVlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vlan Script Generator | Fill the options and press on Generate!.
        /// </summary>
        internal static string lblVlanGen {
            get {
                return ResourceManager.GetString("lblVlanGen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a About.
        /// </summary>
        internal static string OptionAbout {
            get {
                return ResourceManager.GetString("OptionAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit.
        /// </summary>
        internal static string OptionEdit {
            get {
                return ResourceManager.GetString("OptionEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a File.
        /// </summary>
        internal static string OptionFile {
            get {
                return ResourceManager.GetString("OptionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a StackedMinds.
        /// </summary>
        internal static string subOptionAboutCompany {
            get {
                return ResourceManager.GetString("subOptionAboutCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Help.
        /// </summary>
        internal static string subOptionAboutHelp {
            get {
                return ResourceManager.GetString("subOptionAboutHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clear all.
        /// </summary>
        internal static string subOptionEditClean {
            get {
                return ResourceManager.GetString("subOptionEditClean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exit.
        /// </summary>
        internal static string subOptionFileQuit {
            get {
                return ResourceManager.GetString("subOptionFileQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vlan Generator.
        /// </summary>
        internal static string tabVlan {
            get {
                return ResourceManager.GetString("tabVlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vlan Number from 1 to 4094.
        /// </summary>
        internal static string ttVlanNumber {
            get {
                return ResourceManager.GetString("ttVlanNumber", resourceCulture);
            }
        }
    }
}
